### ISSUE TITLE
error en linea

### ISSUE THREAD

**Issue by Rafrobeat** [ivan-abreu/didacticpatternvisualizer#1]
Hola Ivan! gracias por esta herramienta tan chevere. La vi en un taller tuyo y me encantó. Estoy intentando que me corra, y todo funciona bien aparentemente en processing, pero al correr el codigo en tidal cuando ejecuto la siguiente linea,

formatsdpv = OSC "/didacticpatternvisualizer" Named {required = []}

 recibo el siguiente error:

* Constructor `Named' does not have field `required'
    * In the second argument of `OSC', namely `Named {required = []}'
      In the expression:
        OSC "/didacticpatternvisualizer" Named {required = []}
      In an equation for `formatsdpv':
          formatsdpv = OSC "/didacticpatternvisualizer" Named {required = []}

quisiera saber si me puedes guiar.

Lo probé en windows y linux xon versiones tidal 1.9.2 y 1.7.8 y recibo el mismo error en ambos escenarios.

Saludos!

**Comment by ivan-abreu** [comment]
Hola Rafael , actualice el repositorio con la versión de OSC (Tidal) que
uso ahora, hace algún tiempo me estaba dando error y Alex Mclean me
envió esta versión que me funciona,
la encuentras en
https://github.com/ivan-abreu/didacticpatternvisualizer/blob/main/GETTING-STARTED.md

dime como te va
abrazo
Iván

**Comment by Rafrobeat** [comment]
Gracias Ivan! Ahora si me funciona perfecto! Muchas gracias!
